import { notFound } from "next/navigation";
import Link from "next/link";
import { getArticleById } from "@/lib/articles";
import { SentimentBadge } from "@/components/sentiment-badge";
import { LanguageBadge } from "@/components/language-badge";

export default async function ArticlePage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  let article;
  try {
    article = await getArticleById(id);
  } catch {
    notFound();
  }

  if (!article) {
    notFound();
  }

  return (
    <div className="mx-auto max-w-4xl px-4 py-8">
      <Link
        href="/"
        className="mb-6 inline-flex items-center text-sm text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300"
      >
        ← Back to feed
      </Link>

      <article className="rounded-xl border border-gray-200 bg-white p-8 dark:border-gray-800 dark:bg-gray-900">
        <div className="mb-4 flex flex-wrap items-center gap-2">
          <SentimentBadge sentiment={article.sentiment} />
          <LanguageBadge language={article.language} />
          <span className="text-sm text-gray-500 dark:text-gray-400">
            {article.source}
          </span>
          {article.published_at && (
            <span className="text-sm text-gray-500 dark:text-gray-400">
              · {new Date(article.published_at).toLocaleDateString()}
            </span>
          )}
        </div>

        <h1 className="mb-6 text-3xl font-bold text-gray-900 dark:text-white">
          {article.title}
        </h1>

        {article.summary && (
          <div className="mb-6 rounded-lg bg-gray-50 p-4 dark:bg-gray-800">
            <h2 className="mb-2 text-sm font-medium text-gray-500 dark:text-gray-400">
              AI Summary
            </h2>
            <p className="text-gray-700 dark:text-gray-300">
              {article.summary}
            </p>
            {article.enrichment_model && (
              <p className="mt-2 text-xs text-gray-400 dark:text-gray-500">
                Generated by {article.enrichment_model}
              </p>
            )}
          </div>
        )}

        {article.bias_notes && (
          <div className="mb-6 rounded-lg bg-yellow-50 p-4 dark:bg-yellow-900/20">
            <h2 className="mb-2 text-sm font-medium text-yellow-800 dark:text-yellow-200">
              Bias Notes
            </h2>
            <p className="text-sm text-yellow-700 dark:text-yellow-300">
              {article.bias_notes}
            </p>
          </div>
        )}

        {article.body && (
          <div className="prose prose-gray dark:prose-invert max-w-none">
            <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
              {article.body}
            </p>
          </div>
        )}

        <div className="mt-8 border-t border-gray-200 pt-6 dark:border-gray-800">
          <a
            href={article.url}
            target="_blank"
            rel="noopener noreferrer"
            className="text-sm text-blue-600 hover:underline dark:text-blue-400"
          >
            View original article →
          </a>
        </div>
      </article>
    </div>
  );
}
